"""Added status column to expenses

Revision ID: 1d442feb1e24
Revises: 
Create Date: 2025-12-11 15:33:14.936834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d442feb1e24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        # CHANGE TO THIS:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='unpaid'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
